dist: trusty
language: java
jdk:
- oraclejdk8

cache:
  directories:
  - $HOME/.m2

env:
  global:
  - secure: s6Vbm+Vm12wkiQxGqu2SKvp76vPGCwNR/3UGwOSUHEGOJZP18s8x1TwlICUin1Pw9lU72/iqIH4XlKy1uD9QfDlAjqAp/R1uFQsT1T7lReQ0zR6yCmK5yuQy3L7Wixp1nN+Xn2D9kB1bOJinJCK1MUtWJFybASpWO1cw7OMU79YePT197Xm39BIdSZKxj5sBY54Jly54dZdqSDno9/5haWgwonVcyD9XcYRkEVnXWlwwAAODtRaEMv2th14pXNd2wzsiXCf/zAnJu3toNViB4aw2AL+MEnK111shtwyx1hq1NDabA2ur1h91XhWRvqbRH4zL088qd6bfXzaHLw4Gb5TiuB7TuOVJtmg+WZCRUESgzyGNJq5bqQ0NFz0uPeyiWw+2S0J5TBvB6tEvHEqgunAEKLiObtcza+uACeebdtjHA11A3POjmqPGUC3WUVcS9Fw/vqKSdes+woEHVEfWntoHOjM7xqrlnDe9xrSgCqb4zRu5AzLbm5L1j6RahhkatCFDLfvXERu5McXjKxLmtXgdfAAOpmz51TIBedoDFfZIYrkm6nDgpMsU1DckHuayXaWehDK5STGkydSL3wSOySW5s1kOBjYAb5mPGKBpTx6kXUwOYt6r27vMn0ciZS0S6KWBKTfFY2v9ncKOI5WUeqgf44w1G/xr57irBzJuPQo=
  - secure: yMsl63Zm1TwNuQ58NmbwucnslOdWyHGHLzO2wRj6HkjHVah6Kxo5S3hpKLYXJKUDPiUO8toboZoiGdEkDy3qbSMk92muqcqstjrAfsN/Qdov12P2EjSWDqIZU9s9ojP2tETl1VISNv2xN+yXLF2XuYE0/e6qECGGf75PDVhb2jjYngsTATS0IpEbv4PVokdU3ENZdpwOImj0VgBBCUZB0oahQEDi7MsJh2Odnb22a++oObEa9M2Z45vcMsZrvO4eE203N63A/qIsFdGB/RUG81IrWCG2evV123yYnHnVJdT8MVlwBt/ClvcOmMcR72HUyHC+Nf5BQgV+HdggzdiKqlexBYsR+mV778XXc0GRUw2vLnm7Hodq5D24rF407cxVFucnqHoW3XBgN+t9LV74ewc4nIJYn8byjthDNf0pKvoS68qkhrwydC1FYiS5FmaZmn/48EumQsRcJGK6/yfm6ETQtxL2apGPYbAPUPsQJFGHh2r3rNuwp9/wZCH0T+h+7gjVpK+0UK6uvoJHs/zoC+15VB5HuFxGVPibzI4SCMecYGNFRA02eQWLv1ispW6YFpEP21axhRRlD5kJ4gnZKMbGH4FE7sfoKFBQiOjvhXzyzJcHmprmGiPFYidbMqdqA96wTEwaoWgyz3NtahH+82nja4nqCJZd+3jNwlpKGxw=

install: true

before_script:
- cp .travis.maven.settings.xml ~/.m2/settings.xml

script:
- mvn clean deploy
