name: Build and deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '8', '17', '21' ]
    name: Build on Java ${{ matrix.java }}
    env:
      MAVEN_ARGS: --show-version --no-transfer-progress --batch-mode
    steps:
      - name: Checkout ${{ github.ref_name }}
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Set up Java ${{ matrix.java }}
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin
          cache: maven
          gpg-private-key: ${{ secrets.MAVEN_CENTRAL_SIGNING_KEY_PRIVATE }}
          server-id: central
          server-username: MAVEN_CENTRAL_TOKEN_USERNAME
          server-password: MAVEN_CENTRAL_TOKEN_PASSWORD
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
      - name: Activate Artifact Signing and Version Suffix
        run: |
          profiles="build-sources-and-javadoc,deploy-to-maven-central"
          if [[ "${GITHUB_REF_TYPE}" == "tag" ]]; then
            profiles="$profiles,sign-artifacts"
            version_suffix=""
          else
            version_suffix="-SNAPSHOT"         
          fi
          echo "MAVEN_PROFILES=$profiles" >> $GITHUB_ENV
          version="${GITHUB_REF_NAME}${version_suffix}"
          echo "VERSION=$version" >> $GITHUB_ENV
      - name: Set Maven build output version
        run: mvn versions:set -DnewVersion=${VERSION}
      - name: Build
        run: mvn --activate-profiles ${MAVEN_PROFILES} ${{ matrix.java == 8 && 'deploy' || 'verify' }}
        env:
          MAVEN_CENTRAL_TOKEN_USERNAME: ${{ secrets.MAVEN_CENTRAL_TOKEN_USERNAME }}
          MAVEN_CENTRAL_TOKEN_PASSWORD: ${{ secrets.MAVEN_CENTRAL_TOKEN_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_CENTRAL_SIGNING_KEY_PASSPHRASE }}
